// Sample NFL player data for visualization
// In a real application, this would be fetched from an API or database

// Helper function to determine if a player is "elite" (top performers)
const isElitePlayer = (rating) => {
  return rating > 90
}

// Generate sample player data
export const playerData = [
  // Wide Receivers (WR)
  {
    id: 1,
    name: "Justin Jefferson",
    team: "MIN",
    position: "WR",
    manSeparation: 0.42,
    zoneSeparation: 0.31,
    catchRate: 72.5,
    yardsPerRoute: 2.8,
    targetShare: 28.4,
    redZoneTargets: 18,
    overallRating: 94.2,
    isElite: true,
    note: "Elite separator against both man and zone coverage",
  },
  {
    id: 2,
    name: "Tyreek Hill",
    team: "MIA",
    position: "WR",
    manSeparation: 0.38,
    zoneSeparation: 0.22,
    catchRate: 68.7,
    yardsPerRoute: 3.2,
    targetShare: 31.5,
    redZoneTargets: 15,
    overallRating: 93.8,
    isElite: true,
    note: "Speed threat who excels against man coverage",
  },
  {
    id: 3,
    name: "CeeDee Lamb",
    team: "DAL",
    position: "WR",
    manSeparation: 0.35,
    zoneSeparation: 0.28,
    catchRate: 70.2,
    yardsPerRoute: 2.6,
    targetShare: 30.1,
    redZoneTargets: 22,
    overallRating: 92.5,
    isElite: true,
    note: "Well-rounded receiver with excellent route running",
  },
  {
    id: 4,
    name: "Ja'Marr Chase",
    team: "CIN",
    position: "WR",
    manSeparation: 0.33,
    zoneSeparation: 0.25,
    catchRate: 67.8,
    yardsPerRoute: 2.7,
    targetShare: 29.3,
    redZoneTargets: 20,
    overallRating: 91.9,
    isElite: true,
    note: "Physical receiver who wins contested catches",
  },
  {
    id: 5,
    name: "Davante Adams",
    team: "LV",
    position: "WR",
    manSeparation: 0.31,
    zoneSeparation: 0.18,
    catchRate: 65.4,
    yardsPerRoute: 2.3,
    targetShare: 27.8,
    redZoneTargets: 24,
    overallRating: 90.6,
    isElite: true,
    note: "Elite release technique against press coverage",
  },
  {
    id: 6,
    name: "Amon-Ra St. Brown",
    team: "DET",
    position: "WR",
    manSeparation: 0.29,
    zoneSeparation: 0.32,
    catchRate: 74.1,
    yardsPerRoute: 2.4,
    targetShare: 28.9,
    redZoneTargets: 19,
    overallRating: 90.2,
    isElite: true,
    note: "Slot specialist who excels against zone coverage",
  },
  {
    id: 7,
    name: "Stefon Diggs",
    team: "HOU",
    position: "WR",
    manSeparation: 0.27,
    zoneSeparation: 0.26,
    catchRate: 69.3,
    yardsPerRoute: 2.2,
    targetShare: 25.6,
    redZoneTargets: 17,
    overallRating: 88.7,
    isElite: false,
    note: "Precise route runner with good hands",
  },
  {
    id: 8,
    name: "A.J. Brown",
    team: "PHI",
    position: "WR",
    manSeparation: 0.3,
    zoneSeparation: 0.21,
    catchRate: 66.8,
    yardsPerRoute: 2.5,
    targetShare: 26.7,
    redZoneTargets: 16,
    overallRating: 89.4,
    isElite: true,
    note: "Physical receiver who excels after the catch",
  },
  {
    id: 9,
    name: "DeVonta Smith",
    team: "PHI",
    position: "WR",
    manSeparation: 0.28,
    zoneSeparation: 0.24,
    catchRate: 71.5,
    yardsPerRoute: 2.1,
    targetShare: 23.4,
    redZoneTargets: 14,
    overallRating: 87.9,
    isElite: false,
    note: "Smooth route runner with good body control",
  },
  {
    id: 10,
    name: "Keenan Allen",
    team: "CHI",
    position: "WR",
    manSeparation: 0.25,
    zoneSeparation: 0.3,
    catchRate: 73.2,
    yardsPerRoute: 2.0,
    targetShare: 24.8,
    redZoneTargets: 18,
    overallRating: 87.5,
    isElite: false,
    note: "Veteran route runner who finds soft spots in zone",
  },
  {
    id: 11,
    name: "Mike Evans",
    team: "TB",
    position: "WR",
    manSeparation: 0.22,
    zoneSeparation: 0.17,
    catchRate: 62.1,
    yardsPerRoute: 2.2,
    targetShare: 22.3,
    redZoneTargets: 25,
    overallRating: 86.8,
    isElite: false,
    note: "Red zone specialist with size advantage",
  },
  {
    id: 12,
    name: "Cooper Kupp",
    team: "LAR",
    position: "WR",
    manSeparation: 0.26,
    zoneSeparation: 0.29,
    catchRate: 72.8,
    yardsPerRoute: 2.3,
    targetShare: 27.1,
    redZoneTargets: 20,
    overallRating: 88.2,
    isElite: false,
    note: "Excellent at finding space in zone coverage",
  },
  {
    id: 13,
    name: "DK Metcalf",
    team: "SEA",
    position: "WR",
    manSeparation: 0.27,
    zoneSeparation: 0.16,
    catchRate: 63.5,
    yardsPerRoute: 2.1,
    targetShare: 24.2,
    redZoneTargets: 21,
    overallRating: 86.4,
    isElite: false,
    note: "Physical specimen who wins with size and speed",
  },
  {
    id: 14,
    name: "Jaylen Waddle",
    team: "MIA",
    position: "WR",
    manSeparation: 0.32,
    zoneSeparation: 0.19,
    catchRate: 67.9,
    yardsPerRoute: 2.4,
    targetShare: 22.8,
    redZoneTargets: 12,
    overallRating: 87.1,
    isElite: false,
    note: "Speed threat who creates separation with quickness",
  },
  {
    id: 15,
    name: "Chris Olave",
    team: "NO",
    position: "WR",
    manSeparation: 0.24,
    zoneSeparation: 0.23,
    catchRate: 68.4,
    yardsPerRoute: 2.2,
    targetShare: 23.7,
    redZoneTargets: 15,
    overallRating: 85.9,
    isElite: false,
    note: "Smooth route runner with good deep ball tracking",
  },
  {
    id: 16,
    name: "Terry McLaurin",
    team: "WAS",
    position: "WR",
    manSeparation: 0.26,
    zoneSeparation: 0.18,
    catchRate: 64.7,
    yardsPerRoute: 2.0,
    targetShare: 24.5,
    redZoneTargets: 16,
    overallRating: 85.3,
    isElite: false,
    note: "Consistent producer despite quarterback inconsistency",
  },
  {
    id: 17,
    name: "Deebo Samuel",
    team: "SF",
    position: "WR",
    manSeparation: 0.23,
    zoneSeparation: 0.2,
    catchRate: 65.8,
    yardsPerRoute: 2.3,
    targetShare: 21.9,
    redZoneTargets: 14,
    overallRating: 85.7,
    isElite: false,
    note: "Versatile weapon who excels with ball in hands",
  },
  {
    id: 18,
    name: "Tee Higgins",
    team: "CIN",
    position: "WR",
    manSeparation: 0.25,
    zoneSeparation: 0.19,
    catchRate: 66.2,
    yardsPerRoute: 2.1,
    targetShare: 22.6,
    redZoneTargets: 17,
    overallRating: 85.1,
    isElite: false,
    note: "Big-bodied receiver with good contested catch ability",
  },
  {
    id: 19,
    name: "Calvin Ridley",
    team: "TEN",
    position: "WR",
    manSeparation: 0.27,
    zoneSeparation: 0.17,
    catchRate: 63.9,
    yardsPerRoute: 2.0,
    targetShare: 23.1,
    redZoneTargets: 13,
    overallRating: 84.8,
    isElite: false,
    note: "Precise route runner returning to form",
  },
  {
    id: 20,
    name: "Michael Pittman Jr.",
    team: "IND",
    position: "WR",
    manSeparation: 0.21,
    zoneSeparation: 0.22,
    catchRate: 67.5,
    yardsPerRoute: 1.9,
    targetShare: 25.2,
    redZoneTargets: 19,
    overallRating: 84.5,
    isElite: false,
    note: "Reliable possession receiver with good hands",
  },
  // Quarterbacks (QB)
  {
    id: 101,
    name: "Patrick Mahomes",
    team: "KC",
    position: "QB",
    completionPercentage: 67.2,
    yardsPerAttempt: 7.8,
    touchdownPercentage: 6.1,
    interceptionPercentage: 1.9,
    qbRating: 105.2,
    rushingYards: 358,
    rushingTouchdowns: 4,
    overallRating: 96.5,
    isElite: true,
    note: "Elite quarterback who excels in all aspects of the game",
  },
  {
    id: 102,
    name: "Josh Allen",
    team: "BUF",
    position: "QB",
    completionPercentage: 65.8,
    yardsPerAttempt: 7.5,
    touchdownPercentage: 5.8,
    interceptionPercentage: 2.2,
    qbRating: 98.7,
    rushingYards: 762,
    rushingTouchdowns: 7,
    overallRating: 94.8,
    isElite: true,
    note: "Dual-threat quarterback with a powerful arm",
  },
  {
    id: 103,
    name: "Joe Burrow",
    team: "CIN",
    position: "QB",
    completionPercentage: 68.5,
    yardsPerAttempt: 7.6,
    touchdownPercentage: 5.5,
    interceptionPercentage: 2.0,
    qbRating: 100.5,
    rushingYards: 257,
    rushingTouchdowns: 5,
    overallRating: 93.2,
    isElite: true,
    note: "Accurate passer with excellent decision-making skills",
  },
  {
    id: 104,
    name: "Lamar Jackson",
    team: "BAL",
    position: "QB",
    completionPercentage: 64.7,
    yardsPerAttempt: 7.2,
    touchdownPercentage: 5.2,
    interceptionPercentage: 2.1,
    qbRating: 94.8,
    rushingYards: 821,
    rushingTouchdowns: 6,
    overallRating: 92.5,
    isElite: true,
    note: "Dynamic runner with improving passing skills",
  },
  {
    id: 105,
    name: "Justin Herbert",
    team: "LAC",
    position: "QB",
    completionPercentage: 66.9,
    yardsPerAttempt: 7.3,
    touchdownPercentage: 5.0,
    interceptionPercentage: 1.8,
    qbRating: 97.2,
    rushingYards: 302,
    rushingTouchdowns: 3,
    overallRating: 91.8,
    isElite: true,
    note: "Strong-armed quarterback with excellent pocket presence",
  },

  // Running Backs (RB)
  {
    id: 201,
    name: "Christian McCaffrey",
    team: "SF",
    position: "RB",
    rushingYards: 1139,
    rushingTouchdowns: 14,
    receptions: 85,
    receivingYards: 741,
    receivingTouchdowns: 7,
    yardsPerCarry: 5.2,
    yardsPerReception: 8.7,
    totalTouchdowns: 21,
    overallRating: 95.8,
    isElite: true,
    note: "Versatile back who excels in both rushing and receiving",
  },
  {
    id: 202,
    name: "Derrick Henry",
    team: "TEN",
    position: "RB",
    rushingYards: 1538,
    rushingTouchdowns: 13,
    receptions: 28,
    receivingYards: 206,
    receivingTouchdowns: 0,
    yardsPerCarry: 4.8,
    yardsPerReception: 7.4,
    totalTouchdowns: 13,
    overallRating: 94.2,
    isElite: true,
    note: "Power back with exceptional speed for his size",
  },
  {
    id: 203,
    name: "Austin Ekeler",
    team: "LAC",
    position: "RB",
    rushingYards: 915,
    rushingTouchdowns: 13,
    receptions: 107,
    receivingYards: 722,
    receivingTouchdowns: 5,
    yardsPerCarry: 4.5,
    yardsPerReception: 6.7,
    totalTouchdowns: 18,
    overallRating: 93.5,
    isElite: true,
    note: "Dual-threat back who excels in the passing game",
  },
  {
    id: 204,
    name: "Saquon Barkley",
    team: "NYG",
    position: "RB",
    rushingYards: 1312,
    rushingTouchdowns: 10,
    receptions: 57,
    receivingYards: 338,
    receivingTouchdowns: 0,
    yardsPerCarry: 4.9,
    yardsPerReception: 5.9,
    totalTouchdowns: 10,
    overallRating: 92.1,
    isElite: true,
    note: "Explosive back with great vision and cutting ability",
  },
  {
    id: 205,
    name: "Josh Jacobs",
    team: "LV",
    position: "RB",
    rushingYards: 1653,
    rushingTouchdowns: 12,
    receptions: 53,
    receivingYards: 400,
    receivingTouchdowns: 0,
    yardsPerCarry: 4.9,
    yardsPerReception: 7.5,
    totalTouchdowns: 12,
    overallRating: 91.7,
    isElite: true,
    note: "Powerful runner with good balance and vision",
  },

  // Tight Ends (TE)
  {
    id: 301,
    name: "Travis Kelce",
    team: "KC",
    position: "TE",
    receptions: 110,
    receivingYards: 1338,
    receivingTouchdowns: 12,
    yardsPerReception: 12.2,
    catchRate: 72.8,
    targetShare: 25.7,
    redZoneTargets: 22,
    overallRating: 96.2,
    isElite: true,
    note: "Elite receiving tight end with exceptional route running",
  },
  {
    id: 302,
    name: "George Kittle",
    team: "SF",
    position: "TE",
    receptions: 71,
    receivingYards: 910,
    receivingTouchdowns: 6,
    yardsPerReception: 12.8,
    catchRate: 68.9,
    targetShare: 18.5,
    redZoneTargets: 15,
    overallRating: 93.8,
    isElite: true,
    note: "Versatile tight end who excels in both receiving and blocking",
  },
  {
    id: 303,
    name: "Mark Andrews",
    team: "BAL",
    position: "TE",
    receptions: 73,
    receivingYards: 847,
    receivingTouchdowns: 5,
    yardsPerReception: 11.6,
    catchRate: 67.6,
    targetShare: 22.1,
    redZoneTargets: 18,
    overallRating: 92.5,
    isElite: true,
    note: "Reliable target with great hands and red zone presence",
  },
  {
    id: 304,
    name: "T.J. Hockenson",
    team: "MIN",
    position: "TE",
    receptions: 86,
    receivingYards: 914,
    receivingTouchdowns: 6,
    yardsPerReception: 10.6,
    catchRate: 71.7,
    targetShare: 19.8,
    redZoneTargets: 16,
    overallRating: 90.8,
    isElite: true,
    note: "Athletic tight end with good route running and catching ability",
  },
  {
    id: 305,
    name: "Dallas Goedert",
    team: "PHI",
    position: "TE",
    receptions: 55,
    receivingYards: 702,
    receivingTouchdowns: 3,
    yardsPerReception: 12.8,
    catchRate: 72.4,
    targetShare: 15.6,
    redZoneTargets: 12,
    overallRating: 89.5,
    isElite: false,
    note: "Reliable target with good after-the-catch ability",
  },
]

// You can add more players for each position to have a larger dataset

